26-03-2019 12:37:13 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:13 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=72092, type_id=4, value='19084' where id=72095 was aborted.  Call getNextException to see the cause.
26-03-2019 12:37:13 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:13 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19084) already exists.
26-03-2019 12:37:13 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=72092, type_id=4, value='19084' where id=72095 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:37:22 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:22 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=2980949, type_id=4, value='21662' where id=2980952 was aborted.  Call getNextException to see the cause.
26-03-2019 12:37:22 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:22 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 21662) already exists.
26-03-2019 12:37:22 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=2980949, type_id=4, value='21662' where id=2980952 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:37:22 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:22 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=2980949, type_id=4, value='21662' where id=2980952 was aborted.  Call getNextException to see the cause.
26-03-2019 12:37:22 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:22 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 21662) already exists.
26-03-2019 12:37:22 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=2980949, type_id=4, value='21662' where id=2980952 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:37:23 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:23 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=2980949, type_id=4, value='21662' where id=2980952 was aborted.  Call getNextException to see the cause.
26-03-2019 12:37:23 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:23 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 21662) already exists.
26-03-2019 12:37:23 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=2980949, type_id=4, value='21662' where id=2980952 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:37:23 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:23 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=2980949, type_id=4, value='21662' where id=2980952 was aborted.  Call getNextException to see the cause.
26-03-2019 12:37:23 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:23 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 21662) already exists.
26-03-2019 12:37:23 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=2980949, type_id=4, value='21662' where id=2980952 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:37:38 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:38 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=676437, type_id=4, value='20902' where id=676440 was aborted.  Call getNextException to see the cause.
26-03-2019 12:37:38 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:38 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 20902) already exists.
26-03-2019 12:37:38 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=676437, type_id=4, value='20902' where id=676440 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:37:39 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:39 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=676437, type_id=4, value='20902' where id=676440 was aborted.  Call getNextException to see the cause.
26-03-2019 12:37:39 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:39 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 20902) already exists.
26-03-2019 12:37:39 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=676437, type_id=4, value='20902' where id=676440 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:37:42 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:42 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
26-03-2019 12:37:42 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:42 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19262) already exists.
26-03-2019 12:37:42 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:37:42 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:42 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
26-03-2019 12:37:42 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:42 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19262) already exists.
26-03-2019 12:37:42 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:37:46 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:46 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
26-03-2019 12:37:46 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:46 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 20165) already exists.
26-03-2019 12:37:46 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:37:46 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:46 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
26-03-2019 12:37:46 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:46 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 20165) already exists.
26-03-2019 12:37:46 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:37:56 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:56 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=71096, type_id=4, value='199' where id=71099 was aborted.  Call getNextException to see the cause.
26-03-2019 12:37:56 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:56 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 199) already exists.
26-03-2019 12:37:56 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=71096, type_id=4, value='199' where id=71099 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:37:59 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:59 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=1164331, type_id=4, value='20841' where id=1164333 was aborted.  Call getNextException to see the cause.
26-03-2019 12:37:59 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:37:59 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 20841) already exists.
26-03-2019 12:37:59 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=1164331, type_id=4, value='20841' where id=1164333 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:38:14 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:38:14 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=79611, type_id=4, value='19772' where id=79614 was aborted.  Call getNextException to see the cause.
26-03-2019 12:38:14 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:38:14 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19772) already exists.
26-03-2019 12:38:14 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=79611, type_id=4, value='19772' where id=79614 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:38:14 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:38:14 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=79611, type_id=4, value='19772' where id=79614 was aborted.  Call getNextException to see the cause.
26-03-2019 12:38:14 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:38:14 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19772) already exists.
26-03-2019 12:38:14 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=79611, type_id=4, value='19772' where id=79614 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:38:38 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:38:38 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
26-03-2019 12:38:38 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:38:38 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19262) already exists.
26-03-2019 12:38:38 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:38:38 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:38:38 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
26-03-2019 12:38:38 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:38:38 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19262) already exists.
26-03-2019 12:38:38 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:38:49 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:38:49 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=1164331, type_id=4, value='20841' where id=1164333 was aborted.  Call getNextException to see the cause.
26-03-2019 12:38:49 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:38:49 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 20841) already exists.
26-03-2019 12:38:49 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=1164331, type_id=4, value='20841' where id=1164333 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:38:58 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:38:58 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=123920, type_id=4, value='19861' where id=123922 was aborted.  Call getNextException to see the cause.
26-03-2019 12:38:58 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:38:58 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19861) already exists.
26-03-2019 12:38:58 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=123920, type_id=4, value='19861' where id=123922 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:38:58 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:38:58 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=123920, type_id=4, value='19861' where id=123922 was aborted.  Call getNextException to see the cause.
26-03-2019 12:38:58 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:38:58 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19861) already exists.
26-03-2019 12:38:58 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=123920, type_id=4, value='19861' where id=123922 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:39:04 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:39:04 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
26-03-2019 12:39:04 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:39:04 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 20165) already exists.
26-03-2019 12:39:04 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:39:04 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:39:04 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
26-03-2019 12:39:04 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:39:04 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 20165) already exists.
26-03-2019 12:39:04 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:39:11 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:39:11 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=535694, type_id=4, value='20581' where id=535696 was aborted.  Call getNextException to see the cause.
26-03-2019 12:39:11 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:39:11 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 20581) already exists.
26-03-2019 12:39:11 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=535694, type_id=4, value='20581' where id=535696 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:39:15 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:39:15 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=85949, type_id=4, value='2394' where id=85952 was aborted.  Call getNextException to see the cause.
26-03-2019 12:39:15 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:39:15 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 2394) already exists.
26-03-2019 12:39:15 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=85949, type_id=4, value='2394' where id=85952 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:39:20 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:39:20 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=900158, type_id=4, value='20971' where id=900160 was aborted.  Call getNextException to see the cause.
26-03-2019 12:39:20 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:39:20 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 20971) already exists.
26-03-2019 12:39:20 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=900158, type_id=4, value='20971' where id=900160 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:39:47 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:39:47 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=72092, type_id=4, value='19084' where id=72095 was aborted.  Call getNextException to see the cause.
26-03-2019 12:39:47 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:39:47 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19084) already exists.
26-03-2019 12:39:47 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=72092, type_id=4, value='19084' where id=72095 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:41:56 [main] DEBUG celllife.idart.misc.LoginTimer - Terminating iDART - TIMER EXPIRED
26-03-2019 12:41:56 [main] DEBUG dart.start.PharmacyApplication - Logged out..
26-03-2019 12:41:56 [main] DEBUG celllife.idart.gui.login.Login - Login Form Created
26-03-2019 12:43:45 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:43:45 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:43:46 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:43:46 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:44:06 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:44:06 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:44:06 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:44:06 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:44:06 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:44:06 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:44:06 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:44:06 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:44:06 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:44:06 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:44:06 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:44:06 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:44:07 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:44:07 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:44:07 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:44:07 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:44:07 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:44:07 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:44:07 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:44:07 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:44:07 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:44:07 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:44:36 [main] INFO  i.prescription.AddPrescription - Saved Prescription for Patient: 1974721
26-03-2019 12:44:42 [main] INFO  t.gui.composite.PillCountTable - Creating PillCountTable
26-03-2019 12:44:42 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:44:42 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:44:42 [main] INFO  idart.database.dao.ConexaoODBC - A Estabelecer a conexao com MS ACESS.....
26-03-2019 12:44:42 [main] ERROR idart.database.dao.ConexaoODBC - Não foi possivel conectar a base de dados MS ACESS.....
26-03-2019 12:44:42 [main] INFO  idart.database.dao.ConexaoODBC - A Estabelecer a conexao com MS ACESS.....
26-03-2019 12:44:42 [main] ERROR idart.database.dao.ConexaoODBC - Não foi possivel conectar a base de dados MS ACESS.....
26-03-2019 12:44:43 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:44:43 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:44:58 [main] INFO  .packaging.NewPatientPackaging - getSelectedWeekSupply() called
26-03-2019 12:44:58 [main] INFO      model.manager.StockManager - Calculating StockLevel for stock 2161891
26-03-2019 12:45:00 [main] INFO  .packaging.NewPatientPackaging - savePackageAndPackagedDrugs() called
26-03-2019 12:45:00 [main] INFO  anager.TemporaryRecordsManager - Saving package drug infos.
26-03-2019 12:45:00 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:45:01 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:45:01 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:45:01 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:45:01 [main] INFO  idart.database.dao.ConexaoODBC - A Estabelecer a conexao com MS ACESS.....
26-03-2019 12:45:01 [main] ERROR idart.database.dao.ConexaoODBC - Não foi possivel conectar a base de dados MS ACESS.....
26-03-2019 12:45:01 [main] ERROR idart.database.dao.ConexaoODBC - ++++++ Houve erro na Insercao de dados na tabela T_TARV do MS ACESS.....
26-03-2019 12:45:01 [main] ERROR idart.database.dao.ConexaoODBC - java.lang.NullPointerException
26-03-2019 12:45:01 [main] INFO  .packaging.NewPatientPackaging - submitForm() called
26-03-2019 12:45:02 [main] INFO  .packaging.NewPatientPackaging - cmdDispenseDrugsSelected() called
26-03-2019 12:45:43 [main] DEBUG celllife.idart.misc.LoginTimer - Terminating iDART - TIMER EXPIRED
26-03-2019 12:45:43 [main] DEBUG dart.start.PharmacyApplication - Logged out..
26-03-2019 12:45:43 [main] DEBUG celllife.idart.gui.login.Login - Login Form Created
26-03-2019 12:48:12 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:48:12 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:48:14 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:48:14 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:48:39 [main] INFO  t.gui.composite.PillCountTable - Creating PillCountTable
26-03-2019 12:48:56 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:48:56 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:48:56 [main] INFO  idart.database.dao.ConexaoODBC - A Estabelecer a conexao com MS ACESS.....
26-03-2019 12:48:57 [main] ERROR idart.database.dao.ConexaoODBC - Não foi possivel conectar a base de dados MS ACESS.....
26-03-2019 12:48:57 [main] INFO  idart.database.dao.ConexaoODBC - A Estabelecer a conexao com MS ACESS.....
26-03-2019 12:48:57 [main] ERROR idart.database.dao.ConexaoODBC - Não foi possivel conectar a base de dados MS ACESS.....
26-03-2019 12:48:57 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:48:57 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:48:57 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:48:57 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:49:08 [main] INFO  model.manager.DeletionsManager - deleting PackageDrugInfo records for package: 3227698
26-03-2019 12:49:09 [main] INFO  model.manager.DeletionsManager - deleting PackageDrug3227699
26-03-2019 12:49:09 [main] INFO      model.manager.StockManager - Calculating StockLevel for stock 2161891
26-03-2019 12:49:12 [main] INFO  anager.TemporaryRecordsManager - Saving DeletedItems.
26-03-2019 12:49:17 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:49:17 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:49:17 [main] INFO  idart.database.dao.ConexaoODBC - A Estabelecer a conexao com MS ACESS.....
26-03-2019 12:49:17 [main] ERROR idart.database.dao.ConexaoODBC - Não foi possivel conectar a base de dados MS ACESS.....
26-03-2019 12:49:17 [main] INFO  idart.database.dao.ConexaoODBC - A Estabelecer a conexao com MS ACESS.....
26-03-2019 12:49:17 [main] ERROR idart.database.dao.ConexaoODBC - Não foi possivel conectar a base de dados MS ACESS.....
26-03-2019 12:49:18 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:49:18 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:49:26 [main] INFO  .packaging.NewPatientPackaging - getSelectedWeekSupply() called
26-03-2019 12:49:27 [main] INFO      model.manager.StockManager - Calculating StockLevel for stock 2161891
26-03-2019 12:49:29 [main] INFO  .packaging.NewPatientPackaging - savePackageAndPackagedDrugs() called
26-03-2019 12:49:29 [main] INFO  anager.TemporaryRecordsManager - Saving package drug infos.
26-03-2019 12:49:29 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:49:29 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:49:29 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:49:30 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:49:30 [main] INFO  idart.database.dao.ConexaoODBC - A Estabelecer a conexao com MS ACESS.....
26-03-2019 12:49:30 [main] ERROR idart.database.dao.ConexaoODBC - Não foi possivel conectar a base de dados MS ACESS.....
26-03-2019 12:49:30 [main] ERROR idart.database.dao.ConexaoODBC - ++++++ Houve erro na Insercao de dados na tabela T_TARV do MS ACESS.....
26-03-2019 12:49:30 [main] ERROR idart.database.dao.ConexaoODBC - java.lang.NullPointerException
26-03-2019 12:49:30 [main] INFO  .packaging.NewPatientPackaging - submitForm() called
26-03-2019 12:49:31 [main] INFO  .packaging.NewPatientPackaging - cmdDispenseDrugsSelected() called
26-03-2019 12:52:35 [main] INFO  t.gui.composite.PillCountTable - Creating PillCountTable
26-03-2019 12:52:43 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:52:43 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:52:43 [main] INFO  idart.database.dao.ConexaoODBC - A Estabelecer a conexao com MS ACESS.....
26-03-2019 12:52:43 [main] ERROR idart.database.dao.ConexaoODBC - Não foi possivel conectar a base de dados MS ACESS.....
26-03-2019 12:52:43 [main] INFO  idart.database.dao.ConexaoODBC - A Estabelecer a conexao com MS ACESS.....
26-03-2019 12:52:43 [main] ERROR idart.database.dao.ConexaoODBC - Não foi possivel conectar a base de dados MS ACESS.....
26-03-2019 12:52:43 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:52:43 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:52:43 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:52:43 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:52:58 [main] INFO  .packaging.NewPatientPackaging - getSelectedWeekSupply() called
26-03-2019 12:52:59 [main] INFO      model.manager.StockManager - Calculating StockLevel for stock 2558584
26-03-2019 12:52:59 [main] INFO      model.manager.StockManager - Calculating StockLevel for stock 2324660
26-03-2019 12:52:59 [main] INFO  .packaging.NewPatientPackaging - savePackageAndPackagedDrugs() called
26-03-2019 12:52:59 [main] INFO  anager.TemporaryRecordsManager - Saving package drug infos.
26-03-2019 12:52:59 [main] INFO  anager.TemporaryRecordsManager - Saving package drug infos.
26-03-2019 12:52:59 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:52:59 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:52:59 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 12:52:59 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 12:52:59 [main] INFO  idart.database.dao.ConexaoODBC - A Estabelecer a conexao com MS ACESS.....
26-03-2019 12:52:59 [main] ERROR idart.database.dao.ConexaoODBC - Não foi possivel conectar a base de dados MS ACESS.....
26-03-2019 12:52:59 [main] ERROR idart.database.dao.ConexaoODBC - ++++++ Houve erro na Insercao de dados na tabela T_TARV do MS ACESS.....
26-03-2019 12:52:59 [main] ERROR idart.database.dao.ConexaoODBC - java.lang.NullPointerException
26-03-2019 12:52:59 [main] INFO  .packaging.NewPatientPackaging - submitForm() called
26-03-2019 12:53:00 [main] INFO  .packaging.NewPatientPackaging - cmdDispenseDrugsSelected() called
26-03-2019 13:02:20 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 13:02:20 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 13:02:21 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
26-03-2019 13:02:21 [main] INFO  idart.database.dao.ConexaoJDBC - Conectado...Criando a declaração
26-03-2019 13:02:33 [main] INFO  t.gui.composite.PillCountTable - Creating PillCountTable
26-03-2019 13:02:38 [main] INFO  idart.database.dao.ConexaoJDBC - Conectando ao banco de dados
URL = jdbc:postgresql://localhost:5432/pharm
